# Generated by Django 4.2.2 on 2024-08-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("users.can_toggle_status", "Может переключать статус"),
                    ("users.can_see_all_users", "Может видеть всех пользователей"),
                ),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
