# Generated by Django 5.0.7 on 2024-08-05 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="email клиента"),
                ),
                ("comment", models.TextField(verbose_name="комментарий")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="название рассылки"),
                ),
                (
                    "first_send_datetime",
                    models.DateTimeField(verbose_name="дата первого отправления"),
                ),
                (
                    "next_send_datetime",
                    models.DateTimeField(verbose_name="дата следующего отправления"),
                ),
                (
                    "last_send_datetime",
                    models.DateTimeField(verbose_name="дата последнего отправления"),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            (1, "Каждую минуту"),
                            (60, "Каждый час"),
                            (1440, "Ежедневно"),
                            (10080, "Еженедельно"),
                            (43200, "Ежемесячно(каждые 30 дней)"),
                        ],
                        verbose_name="периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Создана"),
                            (1, "Запущена"),
                            (2, "Отменена"),
                            (3, "Завершена"),
                        ],
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(to="mailing.client", verbose_name="клиенты"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingTry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "try_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время и дата попытки"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(editable=False, verbose_name="статус попытки"),
                ),
                (
                    "response",
                    models.TextField(
                        editable=False,
                        null=True,
                        verbose_name="ответ почтового сервера",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.client",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка отправки",
                "verbose_name_plural": "попытки отправки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mail_theme",
                    models.CharField(max_length=150, verbose_name="тема сообщения"),
                ),
                ("message", models.TextField(verbose_name="сообщение")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.message",
                verbose_name="сообщение",
            ),
        ),
    ]
