# Generated by Django 4.2.2 on 2024-08-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_remove_mailingtry_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingtry",
            name="mailing",
        ),
        migrations.AddField(
            model_name="mailing",
            name="mailing_tries",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.mailingtry",
                verbose_name="попытки отправки",
            ),
        ),
    ]
