# Generated by Django 4.2.2 on 2024-08-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_remove_mailingtry_mailing_mailing_mailing_tries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="mailing_tries",
        ),
        migrations.AddField(
            model_name="mailingtry",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.mailing",
                verbose_name="рассылка",
            ),
        ),
    ]
