# Generated by Django 4.2.2 on 2024-08-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_remove_mailing_mailing_tries_mailingtry_mailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": (
                    ("mailing.can_toggle_status", "Можно переключать статус рассылки"),
                    ("mailing.can_see_all_mailings", "Можно видеть все рассылки"),
                ),
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
