# Generated by Django 4.2.2 on 2024-08-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок статьи"),
                ),
                ("content", models.TextField(verbose_name="Содержание статьи")),
                (
                    "image",
                    models.ImageField(
                        upload_to="blog/", verbose_name="Изображение статьи"
                    ),
                ),
                (
                    "count_of_views",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "publieshed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья блога",
                "verbose_name_plural": "Статьи блога",
            },
        ),
    ]
